# syntax=docker.io/docker/dockerfile:1

FROM public.ecr.aws/w2u0w5i6/base/debian:bullseye-slim AS base

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    dpkg-dev g++ gcc libc6-dev pkg-config make autoconf automake \
    zlib1g-dev libssl-dev libffi-dev libreadline-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
