# syntax=docker.io/docker/dockerfile:1

FROM public.ecr.aws/w2u0w5i6/base/alpine:3.21 AS base

RUN apk add --no-cache \
    sudo bash git curl ca-certificates tar xz \
    musl-dev gcompat gcc g++ pkgconfig make autoconf automake \
    zlib-dev openssl-dev libffi-dev readline-dev tcl-dev tk-dev gdb \
    && rm -rf /var/cache/apk/* \
    && ln -s /var/cache/apk /etc/apk/cache
