# syntax=docker.io/docker/dockerfile:1

FROM public.ecr.aws/w2u0w5i6/base/alpine:3.21 AS base

RUN apk add --no-cache \
    sudo bash git curl ca-certificates tar xz make gcc g++ musl-dev autoconf automake \
    && rm -rf /var/cache/apk/* \
    && ln -s /var/cache/apk /etc/apk/cache
