---
name: 'Schedule tests'

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  schedule-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'setup go'
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - run: go version

      - name: 'run tests'
        run: |
          go test -run 'TestPull.*' ./... -v
          go test -run 'TestExec.*' ./... -v
